// <auto-generated />
namespace MediX.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class subcategorytableadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(subcategorytableadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202207071600416_sub category table added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
